# Generated by Django 3.2.5 on 2021-10-19 02:09

from django.db import migrations

from project.settings import DEFAULT_ADMINISTRATOR_USERNAME, DEFAULT_ADMINISTRATOR_PASSWORD, DEFAULT_ADMINISTRATOR_EMAIL
from users.models import User


def create_default_administrator_credentials(apps, schema_editor):
    administrator = User(
        first_name='Administrador', last_name='de Sistemas', username=DEFAULT_ADMINISTRATOR_USERNAME,
        email=DEFAULT_ADMINISTRATOR_EMAIL, is_staff=True, is_superuser=True, is_active=True
    )
    administrator.set_password(DEFAULT_ADMINISTRATOR_PASSWORD)
    administrator.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_initial_groups'),
    ]

    operations = [
        migrations.RunPython(create_default_administrator_credentials),
    ]
