# Generated by Django 3.2.5 on 2021-11-12 12:37

from django.contrib.auth.models import Group, Permission
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations

GROUPS_PERMISSIONS = [
    {'group': 'Administrador', 'permissions': ['__all__'], },
    {'group': 'Ouvinte', 'permissions': [
        'view_audiobook',
    ], },
    {'group': 'Narrador', 'permissions': [
        'view_book',
        'add_book',
        'change_book',
        'delete_book',
        'view_audiobook',
        'add_audiobook',
        'change_audiobook',
        'delete_audiobook',
    ], },
]


def add_permissions_to_group(group, permissions):
    for permission in permissions:
        group.permissions.add(permission)


def add_permission_to_groups(apps, schema_editor):
    emit_post_migrate_signal(2, False, 'default')
    permissions = Permission.objects.all()

    for group_permissions in GROUPS_PERMISSIONS:
        group = Group.objects.filter(name=group_permissions['group']).first()
        permissions_lst = group_permissions['permissions']

        if permissions_lst == ['__all__']:
            add_permissions_to_group(group, permissions)
            continue

        add_permissions_to_group(group, permissions.filter(codename__in=permissions_lst))


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '__latest__'),
        ('auth', '__latest__'),
        ('audiobooks', '0001_initial'),
        ('users', '0003_auto_20211019_0209'),
    ]

    operations = [
        migrations.RunPython(add_permission_to_groups),
    ]
