# Generated by Django 3.2.5 on 2021-11-05 02:07

import audiobooks.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narration_type', models.CharField(choices=[('M', 'Masculina'), ('F', 'Feminina')], max_length=1, verbose_name='Tipo de Narração')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('publishing_company', models.CharField(max_length=64, verbose_name='Editora')),
                ('edition', models.PositiveIntegerField(verbose_name='Edição')),
                ('isbn_10', models.CharField(max_length=10, verbose_name='ISBN 10')),
                ('isbn_13', models.CharField(max_length=13, verbose_name='ISBN 13')),
                ('front_cover', models.ImageField(max_length=255, storage=project.storage.OverwriteStorage(), upload_to=audiobooks.models.front_cover_directory_path, verbose_name='Foto de Capa')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('main', models.BooleanField(verbose_name='Principal')),
                ('sequence', models.PositiveSmallIntegerField(null=True, verbose_name='Sequência')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audiobooks.book', verbose_name='Livro')),
                ('subchapters', models.ManyToManyField(blank=True, to='audiobooks.Chapter', verbose_name='Subcapítulos')),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Autor')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiobooks.book', verbose_name='Livro')),
            ],
        ),
        migrations.CreateModel(
            name='AudioBookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_file', models.FileField(max_length=255, storage=project.storage.OverwriteStorage(), upload_to=audiobooks.models.recording_file_directory_path, verbose_name='Gravação')),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiobooks.audiobook', verbose_name='Audiobook')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiobooks.chapter', verbose_name='Capítulo')),
            ],
        ),
        migrations.AddField(
            model_name='audiobook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiobooks.book', verbose_name='Livro'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='storyteller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Narrador'),
        ),
    ]
