# Generated by Django 3.2.5 on 2021-11-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=2021, verbose_name='Ano'),
            preserve_default=False,
        ),
    ]
