# Generated by Django 3.2.5 on 2021-11-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0003_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobookchapter',
            name='pages_quantity',
            field=models.IntegerField(default=0, verbose_name='Qtd. Páginas do Capítulo'),
        ),
        migrations.AddField(
            model_name='audiobookchapter',
            name='start_page',
            field=models.IntegerField(default=0, verbose_name='Página Inicial do Capítulo'),
        ),
    ]
